repository:
  name: config-loader
  default_branch: main
  private: false
  has_issues: true
  has_wiki: false
  has_projects: false
  allow_squash_merge: true
  allow_merge_commit: false
  delete_branch_on_merge: true
  topics: typescript, aws
collaborators:
  - username: rlmartin
    permission: admin
teams: []
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        require_code_owner_reviews: true
      required_status_checks: null
      enforce_admins: null
      required_linear_history: null
      restrictions: null
